/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx}", "./lib/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // Auralis "Dusk Pastel" design system (from Stitch)
        background: "#f8f9fa",
        "on-background": "#191c1d",
        surface: "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#49454f",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        outline: "#7a757f",
        "outline-variant": "#cbc4d0",
        "surface-tint": "#67558c",
        primary: "#67558c",
        "on-primary": "#ffffff",
        "primary-container": "#b19cd9",
        "on-primary-container": "#443267",
        "primary-fixed": "#ebddff",
        "primary-fixed-dim": "#d2bcfb",
        "inverse-primary": "#d2bcfb",
        secondary: "#006c52",
        "on-secondary": "#ffffff",
        "secondary-container": "#8ff6d0",
        "on-secondary-container": "#007257",
        tertiary: "#78555e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c59ba6",
        "tertiary-fixed": "#ffd9e2",
        "tertiary-fixed-dim": "#e7bbc6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        display: ['"Playfair Display"', "serif"],
        headline: ['"Playfair Display"', "serif"],
        body: ['"DM Sans"', "sans-serif"],
        label: ['"DM Sans"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "1.3" }],
        "title-md": ["18px", { lineHeight: "1.5", letterSpacing: "0.01em" }],
        "body-md": ["16px", { lineHeight: "1.6" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.08em" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      width: {
        "sidebar-width": "280px",
      },
      margin: {
        "sidebar-width": "280px",
      },
      spacing: {
        gutter: "24px",
        "margin-x": "40px",
        "margin-y": "32px",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
    },
  },
  plugins: [],
};
